# ─────────────────────────────────────────────
# Kitty — Socrates / Classical Dark
# ─────────────────────────────────────────────

# Fonte
# font_family      JetBrainsMono Nerd Font Medium
# bold_font        JetBrainsMono Nerd Font Bold
# italic_font      JetBrainsMono Nerd Font Medium Italic
# bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0

# Fundo e texto
background            #171512
foreground            #E8DFCF
background_opacity 0.87
dynamic_background_opacity yes

# Cursor
cursor                 #C79A52
cursor_text_color      #171512

# Seleção
selection_background   #743028
selection_foreground   #E8DFCF

# URLs
url_color              #C79A52

# Bordas
active_border_color    #C79A52
inactive_border_color  #332B24

# ── ANSI Colors ──

# Black
color0   #171512
color8   #51483D

# Red
color1   #9E3F32
color9   #BC5545

# Green
color2   #78845B
color10  #96A46F

# Yellow
color3   #C79A52
color11  #D8B46F

# Blue — cinza/pedra para não introduzir azul
color4   #817566
color12  #A89B88

# Magenta — vinho
color5   #743028
color13  #9E5146

# Cyan — bronze/ocre
color6   #B57A3D
color14  #C99655

# White
color7   #D8C5A1
color15  #E8DFCF

shell /usr/bin/zsh


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
